- block:
  - include_role: {name: bluemind/hardstop}
    tags: [stop, hardstop, teleport_stop]
  - include_role: {name: bluemind/presync}
    tags: [presync, teleport_presync]
  - include_role: {name: bluemind/restart}
    tags: [restart, start, teleport_restart]
  delegate_to: "{{bluemind_baremetal}}"
- setup: {}
  tags: [facts, teleport_facts]
- include_role: {name: bluemind/configure}
  tags: [configure, teleport_configure]
- include_role: {name: bluemind/sync}
  tags: [sync, teleport_sync]
