- shell: |-
    set -ex
    {{bluemind_sync_rsyncd}} {{bluemind_sync_rsync_orig}}/ {{bluemind_sync_rsync_dest}}/
  tags: [presync_sync]
- shell: prout
- shell: |-
    set -ex
    d="{{bluemind_sync_rsync_dest}}"
    for i in \
        $d/var/lib/cyrus              \
        $d/var/lib/postgresql         \
        $d/var/spool/bm-docs          \
        $d/var/spool/bm-elasticsearch \
        $d/var/spool/bm-hsm           \
        $d/var/spool/cyrus            \
        $d/var/spool/sieve            \
        ;do
        if [ -h "$i" ];then rm -fv $i;fi
        if [ ! -d "$i" ];then mkdir -pv $i;fi
    done
  tags: [presync_layout]
