---
- template:
    src: "{{item}}"
    dest: "/sbin/{{item}}"
    mode: "0750"
    force: true
    trim_blocks: false
  tags: [sync, sync_conf]
  loop: [bm-sync.sh, bm-post-sync.sh, bm-change-url.sh]
- shell: /sbin/bm-sync.sh
  tags: [sync, sync_exec]
- include_role: {name: bluemind/dataprotect}
  tags: [sync, sync_dataprotect]
