# bug for 1804 and earlier: OPENSSL_CONF undef prevents installer from creating correctly dhparams:
#   libssl_conf.so: cannot open shared object file: No such file or directory
- blockinfile:
    unsafe_writes: true
    dest: "{{item}}"
    marker: "# {mark} bluemind OPENSSLBUG"
    insertafter: EOF
    block: |
      #
      export OPENSSL_CONF=${OPENSSL_CONF-/etc/ssl}
      #
  loop: [/etc/profile, /etc/bash.bashrc]
# we must also catch non loginshell (like apt modules call by using environment: {{bluemind_exec_env}}
- include_role: {name: corpusops.roles/simpleconfigs/wrapper}
  vars:
    configitems:
    - dest: /etc/systemd/system/bm-nginx.service.d/sslenv.conf
- shell: systemctl daemon-reload
  when: simpleconfigitem.changed
