- block:
  - include_role: {name: bluemind/apt}
  - package:
      cache_valid_time: 1
      update_cache: yes
      upgrade: dist
      allow_unauthenticated: yes
      force_apt_get: true
  tags: [upgrade_apt_dist_upgrade]
- name: launch database upgrade
  shell: bm-cli setup upgrade
  tags: [upgrade_db]
- shell: qsdf
