# reconfigure bm's ini files
- assert: {that: "bluemind_version != bluemind_dest_version"}
- include_role: {name: bluemind/dataprotect}
  vars: {bluemind_dataprotect: false}
  tags: [upgrade_dataprotect]
- include_role: {name: bluemind/aptupgrade}
  tags: [upgrade_apt]
- include_role: {name: bluemind/configure}
  tags: [upgrade_configure]
- include_role: {name: bluemind/disable_crons}
  tags: [upgrade_disable_crons]
# 368m14,872s
- when: force_redo_replication|default(false)
  block:
  - shell: bm-cli replication prepare
    changed_when: false
    tags: [prepare]
  - name: do replication preparation
    shell: bm-cli replication run
    tags: [run]
  tags: [upgrade_prepare_replication]
# 7m
- include_role: {name: bluemind/upgrade}
  tags: [upgrade_apt_migrate]
  vars:
    bluemind_version: "{{bluemind_dest_version}}"
    bluemind_subscription_file: "{{bluemind_dest_subscription_file}}"
- include_role: {name: bluemind/dataprotect/notinprogress}
  tags: [upgrade_dataprotect]
- pause: {prompt: "launch spools migrations"}
  tags: [upgrade_bm4_sub_prompt]
- name: disable ES FS checks
  include_role: {name: bluemind/toggle_es_checks}
  vars: {toggle_es_checks_cluster_enable: true}
# 700s/15m
- name: index mails
  shell: bm-cli mail indexreplicated
  tags: [upgrade_index_index]
- name: imap default folders
  shell: |-
    set -ex
    domains=$(PGPASSWORD=bj psql -qtA -h localhost bj bj -c "select array_to_string(array(select name from
    t_domain), ' ');")
    for domain in ${domains}; do
      time bm-cli maintenance repair --ops mailboxDefaultFolders ${domain}
    done
  tags: [upgrade_defaultfolders]
- name: analyze
  shell: |-
    set -ex
    domains=$(PGPASSWORD=bj psql -qtA -h localhost bj bj -c "select array_to_string(array(select name from
    t_domain), ' ');")
    for domain in ${domains}; do
     time bm-cli maintenance repair --ops replication.subtree ${domain}
    done
  tags: [upgrade_analyze_tree]
- name: reindex parentUid domains
  shell: |-
    set -ex
    domains=$(PGPASSWORD=bj psql -qtA -h localhost bj bj -c "select array_to_string(array(select name from
    t_domain), ' ');")
    for domain in ${domains}; do
     time bm-cli maintenance repair --ops replication.parentUid ${domain}
    done
  tags: [upgrade_analyze_domains]
#3m
- name: bluemind can now reindex
  shell: |-
    set -ex
    rm -f /etc/bm/no.mail.indexing
    systemctl restart bm-core
  tags: [upgrade_bm_nowreindex]
# 50s
# 2h
- name: consolidate mails indexes
  shell: |-
    domains=$(PGPASSWORD=bj psql -qtA -h localhost bj bj -c "select array_to_string(array(select name from
    t_domain), ' ');")
    for domain in ${domains}; do
     bm-cli maintenance consolidateIndex ${domain}
    done
  tags: [upgrade_index_consolidate]
- name: "consolidate contacts - todos - cals"
  include_role: {name: bluemind/reconsolidate}
  tags: [upgrade_reconsolidate]
# 7m
- name: HSM migration
  shell: /usr/share/bm-cyrus/bm-hsm35-migrate-4.sh
  tags: [upgrade_hsm]
- name: renable ES FS checks
  include_role: {name: bluemind/toggle_es_checks}
  vars: {toggle_es_checks_cluster_enable: false}
- include_role: {name: bluemind/crons}
  tags: [upgrade_crons]
